### Principal Component Analysis

In [2]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import matrix_power
import scipy
from scipy.linalg import sqrtm

Выбираем матрицу Q размера kxk.  
Вычисляем $$\Sigma = Q^T \dot Q$$
Рассматриваем ее в качестве ковариационной матрицы.

In [3]:
k = 10
n = 3
Q = np.random.rand(k,k)
S = Q.T.dot(Q)

Собственные значения и собственные векторы матрицы S:

In [4]:
eigenValues, eigenMatrix = eig(S)

Ковариационная матрица S*:

In [5]:
covarMatrix = np.zeros([k,k])

In [6]:
for i in range(k):
    eigenVector = eigenMatrix[:,i]
    s = eigenValues[i] * (eigenVector.reshape(k,1).dot(eigenVector.reshape(1,k)))
    covarMatrix = covarMatrix + s

In [7]:
covarMatrix

array([[ 4.11511798,  2.60304625,  3.64212196,  2.55667865,  2.54299712,
         3.31426421,  4.07218392,  3.55972773,  3.38213541,  2.63967798],
       [ 2.60304625,  4.15143507,  2.78486496,  2.6401192 ,  2.06791063,
         2.32297012,  3.76287237,  3.17272473,  3.70508459,  2.10570208],
       [ 3.64212196,  2.78486496,  4.29807923,  2.57650608,  1.90300506,
         3.64484917,  3.76856276,  3.39423426,  2.81571464,  2.37320227],
       [ 2.55667865,  2.6401192 ,  2.57650608,  2.32930653,  1.69595903,
         2.14010047,  2.59065088,  2.58338063,  2.74175207,  1.76339432],
       [ 2.54299712,  2.06791063,  1.90300506,  1.69595903,  2.21685042,
         2.19018405,  2.96867146,  2.51923602,  2.49528012,  1.87192588],
       [ 3.31426421,  2.32297012,  3.64484917,  2.14010047,  2.19018405,
         3.85925094,  3.60082766,  3.30217181,  2.49525611,  2.37744016],
       [ 4.07218392,  3.76287237,  3.76856276,  2.59065088,  2.96867146,
         3.60082766,  5.4917685 ,  4.23915991

In [8]:
S

array([[ 4.11511798,  2.60304625,  3.64212196,  2.55667865,  2.54299712,
         3.31426421,  4.07218392,  3.55972773,  3.38213541,  2.63967798],
       [ 2.60304625,  4.15143507,  2.78486496,  2.6401192 ,  2.06791063,
         2.32297012,  3.76287237,  3.17272473,  3.70508459,  2.10570208],
       [ 3.64212196,  2.78486496,  4.29807923,  2.57650608,  1.90300506,
         3.64484917,  3.76856276,  3.39423426,  2.81571464,  2.37320227],
       [ 2.55667865,  2.6401192 ,  2.57650608,  2.32930653,  1.69595903,
         2.14010047,  2.59065088,  2.58338063,  2.74175207,  1.76339432],
       [ 2.54299712,  2.06791063,  1.90300506,  1.69595903,  2.21685042,
         2.19018405,  2.96867146,  2.51923602,  2.49528012,  1.87192588],
       [ 3.31426421,  2.32297012,  3.64484917,  2.14010047,  2.19018405,
         3.85925094,  3.60082766,  3.30217181,  2.49525611,  2.37744016],
       [ 4.07218392,  3.76287237,  3.76856276,  2.59065088,  2.96867146,
         3.60082766,  5.4917685 ,  4.23915991

In [9]:
R = sqrtm(S)

In [10]:
R

array([[ 1.17792285,  0.12454986,  0.7357267 ,  0.47697024,  0.49285415,
         0.5334753 ,  0.69361434,  0.51319634,  0.65566427,  0.49136606],
       [ 0.12454986,  1.40619628,  0.43222562,  0.6055152 ,  0.27760947,
         0.25438335,  0.70315863,  0.43602887,  0.83155279,  0.29539058],
       [ 0.7357267 ,  0.43222562,  1.36572671,  0.52017657,  0.06977285,
         0.80526828,  0.57619674,  0.51955617,  0.27609979,  0.3204305 ],
       [ 0.47697024,  0.6055152 ,  0.52017657,  0.84689063,  0.29709882,
         0.27476203,  0.18256564,  0.42954658,  0.51982556,  0.30907749],
       [ 0.49285415,  0.27760947,  0.06977285,  0.29709882,  0.90889682,
         0.42255613,  0.55431125,  0.40358336,  0.45286721,  0.35194591],
       [ 0.5334753 ,  0.25438335,  0.80526828,  0.27476203,  0.42255613,
         1.33118929,  0.52466222,  0.5760173 ,  0.22019265,  0.42405561],
       [ 0.69361434,  0.70315863,  0.57619674,  0.18256564,  0.55431125,
         0.52466222,  1.53553207,  0.7245094 

In [12]:
X = np.random.randn(n,k)

X1 = R.dot(X.T)
X1

array([[-2.0430543 , -2.39156199, -1.07782405],
       [-0.56776666,  1.1290388 , -0.66360118],
       [-2.19920834, -0.85265529, -1.82948271],
       [-1.62934451,  0.07934668, -1.22143678],
       [-1.96648631, -1.6599363 ,  0.00838631],
       [-2.83469958, -1.75782076, -1.35496206],
       [-2.10716974, -2.4449759 , -0.23357227],
       [-2.02525837, -2.06074634, -0.75457154],
       [-0.17991648, -0.52142741, -0.70447727],
       [-2.026317  , -1.83952617, -0.5371448 ]])

In [13]:
X1.shape

(10, 3)

### Principal Component Analysis 

In [14]:
estimateMatrix = np.zeros([k,k])

for i in range(n):
    vector = X1.T[i]
    s = vector.reshape(k,1).dot(vector.reshape(1,k))/(n-1)
    estimateMatrix = estimateMatrix + s
    
estimateMatrix

array([[ 5.52767216, -0.41247142,  4.25207026,  2.22778537,  3.98921995,
         5.7278966 ,  5.20206171,  4.9397054 ,  1.18695382,  4.55908205],
       [-0.41247142,  1.01872706,  0.75000158,  0.91260993, -0.38159615,
         0.26197724, -0.70454655, -0.33802692, -0.00953463, -0.28498563],
       [ 4.25207026,  0.75000158,  4.45527269,  2.87510507,  2.86236197,
         5.1058949 ,  3.57307166,  3.79577348,  1.06455032,  3.50373604],
       [ 2.22778537,  0.91260993,  2.87510507,  2.07648361,  1.53106494,
         3.06711272,  1.76229924,  2.02899582,  0.55612341,  1.90584829],
       [ 3.98921995, -0.38159615,  2.86236197,  1.53106494,  3.31126362,
         4.24045263,  4.10013293,  3.69851122,  0.6067158 ,  3.51685811],
       [ 5.7278966 ,  0.26197724,  5.1058949 ,  3.06711272,  4.24045263,
         6.48068886,  5.29375206,  5.19291878,  1.19056253,  4.85268403],
       [ 5.20206171, -0.70454655,  3.57307166,  1.76229924,  4.10013293,
         5.29375206,  5.23631372,  4.74114263

In [15]:
estEigenValues, estEigenMatrix = eig(estimateMatrix)

Now we're ready to find principal components:

In [16]:
F = np.zeros((n,k,1))

In [19]:
for i in range(n):
    vector = X1.T[i]
    F[i] = estEigenMatrix.T.dot(vector.reshape(k,1))

/home/dasha/opt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  app.launch_new_instance()


 Обнуляем второстепенные компоненты:

In [20]:
F[:, -4:] = 0
F

array([[[  5.96097612e+00],
        [  7.92789878e-01],
        [ -6.39308175e-01],
        [ -1.60982339e-15],
        [  1.99840144e-15],
        [  1.22124533e-15],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00]],

       [[  4.88440110e+00],
        [ -1.85094512e+00],
        [  4.12177614e-01],
        [ -1.33226763e-15],
        [  1.55431223e-15],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00]],

       [[  2.47162173e+00],
        [  1.74579985e+00],
        [  7.27320025e-01],
        [ -1.80411242e-16],
        [  1.38777878e-15],
        [ -1.16573418e-15],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00],
        [  0.00000000e+00]]])

In [21]:
X2 = np.zeros((n,k))
X2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
for i in range(n):
    X2[i] = estEigenMatrix.dot(F[i].reshape((k)))
    
X2 = X2.T

/home/dasha/opt/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  from ipykernel import kernelapp as app


In [23]:
X2

array([[-2.0430543 , -2.39156199, -1.07782405],
       [-0.56776666,  1.1290388 , -0.66360118],
       [-2.19920834, -0.85265529, -1.82948271],
       [-1.62934451,  0.07934668, -1.22143678],
       [-1.96648631, -1.6599363 ,  0.00838631],
       [-2.83469958, -1.75782076, -1.35496206],
       [-2.10716974, -2.4449759 , -0.23357227],
       [-2.02525837, -2.06074634, -0.75457154],
       [-0.17991648, -0.52142741, -0.70447727],
       [-2.026317  , -1.83952617, -0.5371448 ]])

In [24]:
X1

array([[-2.0430543 , -2.39156199, -1.07782405],
       [-0.56776666,  1.1290388 , -0.66360118],
       [-2.19920834, -0.85265529, -1.82948271],
       [-1.62934451,  0.07934668, -1.22143678],
       [-1.96648631, -1.6599363 ,  0.00838631],
       [-2.83469958, -1.75782076, -1.35496206],
       [-2.10716974, -2.4449759 , -0.23357227],
       [-2.02525837, -2.06074634, -0.75457154],
       [-0.17991648, -0.52142741, -0.70447727],
       [-2.026317  , -1.83952617, -0.5371448 ]])

In [25]:
np.sum(X2 - X1)

-1.1374581831979924e-14